### ISSUE TITLE
Initial Single Elimination

### ISSUE THREAD

**Issue by russleyshaw** [siggame/tourneyjs#1]
- [x] should accept an array of strings as combatant ids
- [x] should allow seeding Elo to be set
- [x] should seed based on Elo
- [x] should expose a function to pit two combatants against each other and callback winner
- [ ] should represent ties as a `null` player winning

**Comment by user404d** [comment]
Elo should be done by the service providing the list of teams. The teams are seeded in the tournament based on the order that they appear in the list of teams.

TODO:

 - async tournament play
 - async tournament export/backup
 - import of backed up tournament
 - ties should be reported to the match and stored as meta data

**Comment by russleyshaw** [comment]
import/export/backup is out of the scope of this package.

**Comment by russleyshaw** [comment]
Proposed JS API
```javascript

// load eliminations
import { Elimination } from './tourneyjs';

// build competitors
const competitors = ['dee', 'charlie', 'frank', ...];

// initialize tournament without elo seeding
let tny = Elimination.Single(competitors);

// define a function implementing the playing of 2 competitors
// this function is called any time two competitors need to fight
// (err: Error, winner: any) => void
function fight(competitor1, competitor2, callback) {
    return callback(null, rand.choice(competitor1, competitor2));
}

//play the tournament, using the fight functionality
tny.play(fight) //return a promise of the winner
    .then((winner) => { 
        do stuff with winner;
    })
    .catch(... some error);

**Comment by user404d** [comment]
Ties should be handled by users of the library.
